### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by jianlai123-123** [zhenhuat/STCFormer#8]
你好，十分感谢您的工作。请问可以看一下dataset文件夹的整体结构并且包含什么样的数据文件嘛。我运行时出现数据的问题：FileNotFoundError: [Errno 2] No such file or directory: '/tangzhenhua2/video_pose/MHFormer-main-old/dataset/data_3d_h36m.npz。期待您的回复，谢谢。

**Comment by zhenhuat** [comment]
> 你好，十分感谢您的工作。请问可以看一下dataset文件夹的整体结构并且包含什么样的数据文件嘛。我运行时出现数据的问题：FileNotFoundError: [Errno 2] No such file or directory: '/tangzhenhua2/video_pose/MHFormer-main-old/dataset/data_3d_h36m.npz。期待您的回复，谢谢。

您好，您需要先下载数据文件，然后修改数据路径。具体来说您需要先在[这里](https://drive.google.com/file/d/1FMgAf_I04GlweHMfgUKzB0CMwglxuwPe/view)下载数据集，然后把common/opt.py 的第22行改成您下载好的数据集的地址。

**Comment by jianlai123-123** [comment]
谢谢您的解答。

**Comment by jianlai123-123** [comment]
您好，我去跑了可视化代码，发现跑不通。然后我把MHFormer中的checkpoint文件拿到本项目的checkpoint中
<img width="186" alt="image" src="https://github.com/zhenhuat/STCFormer/assets/117512033/5a473f84-c4e5-4657-93ef-977b556fc8f3">
然后修改了vis代码：
<img width="458" alt="image" src="https://github.com/zhenhuat/STCFormer/assets/117512033/931b2df2-4460-46d5-ac94-20bb30e81e45">
并且把opt中改了一下：
<img width="529" alt="image" src="https://github.com/zhenhuat/STCFormer/assets/117512033/1cb99331-e700-4bbf-a467-a1d2818dd08d">
最终运行结果为：
Traceback (most recent call last):
  File "/.../STCFormer-main/demo/vis.py", line 301, in <module>
    get_pose3D(video_path, output_dir)
  File "/.../STCFormer-main/STCFormer-main/demo/vis.py", line 152, in get_pose3D
    model_dict[name] = pre_dict[name]
KeyError: 'pose_emb.weight'
请问这种是什么原因呢？或者我这样的过程对吗？期待您的回复，十分感谢。

**Comment by zhenhuat** [comment]
> 您好，我去跑了可视化代码，发现跑不通。然后我把MHFormer中的checkpoint文件拿到本项目的checkpoint中 <img alt="image" width="186" src="https://private-user-images.githubusercontent.com/117512033/300736901-5a473f84-c4e5-4657-93ef-977b556fc8f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTU0MjQsIm5iZiI6MTcwNjYxNTEyNCwicGF0aCI6Ii8xMTc1MTIwMzMvMzAwNzM2OTAxLTVhNDczZjg0LWM0ZTUtNDY1Ny05M2VmLTk3N2I1NTZmYzhmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMTQ1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTE1NWI5NzE4ODFlM2VkYzQ4OGYxNDJlOTA4MmUyNTEzY2Q0ODM4ZmM2NTZmYjE4OTM5MjQ4ZmM1MTNkNThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7-9cJS2ooouAipi1nxZ5PaegJUYRDSfcHsdMlzYgnH8"> 然后修改了vis代码： <img alt="image" width="458" src="https://private-user-images.githubusercontent.com/117512033/300737247-931b2df2-4460-46d5-ac94-20bb30e81e45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTU0MjQsIm5iZiI6MTcwNjYxNTEyNCwicGF0aCI6Ii8xMTc1MTIwMzMvMzAwNzM3MjQ3LTkzMWIyZGYyLTQ0NjAtNDZkNS1hYzk0LTIwYmIzMGU4MWU0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMTQ1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDc3Mzg4NDlkYzI5MmE5MDkwNzM5YWNjMzRkYTMxZDA3OWQwMGQwMmFhNmJlOTM2NTkwNmZlNTEwYTMzMWE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5UGXPmPkGyWOJvxrfTxOh2EBVmzypJgM1R07Hm-E5UA"> 并且把opt中改了一下： <img alt="image" width="529" src="https://private-user-images.githubusercontent.com/117512033/300737600-1cb99331-e700-4bbf-a467-a1d2818dd08d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTU0MjQsIm5iZiI6MTcwNjYxNTEyNCwicGF0aCI6Ii8xMTc1MTIwMzMvMzAwNzM3NjAwLTFjYjk5MzMxLWU3MDAtNGJiZi1hNDY3LWExZDI4MThkZDA4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMTQ1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjVlZmI5NzkwZjA1ZGNhZjZiY2M3Nzg5NzcxNzk3MTM4YTIzMzNjZjI4YTZkNjU1ZjdiNDBiZjU2OTk1YjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CqqARqGqaSoRIdW6H37z8qeY19yuwdQLL9fnEqhOJzw"> 最终运行结果为： Traceback (most recent call last): File "/.../STCFormer-main/demo/vis.py", line 301, in get_pose3D(video_path, output_dir) File "/.../STCFormer-main/STCFormer-main/demo/vis.py", line 152, in get_pose3D model_dict[name] = pre_dict[name] KeyError: 'pose_emb.weight' 请问这种是什么原因呢？或者我这样的过程对吗？期待您的回复，十分感谢。

您好，我不确定您的第一个是什么问题，你需要把错误给我看。第二个问题，因为你用的MHFomormer的参数，用的stcformer的模型，自然是不互通的，报的错误是说节点对不上

**Comment by jianlai123-123** [comment]
您好，在运行命令 python demo/vis.py --video sample_video.mp4进行可视化的时候，请问checkpoint中要加入其他的文件嘛。运行的时候出现这个问题：Traceback (most recent call last):
  File "demo/vis.py", line 299, in <module>
    get_pose3D(video_path, output_dir)
  File "demo/vis.py", line 147, in get_pose3D
    model_path = sorted(glob.glob(os.path.join(args.previous_dir, '*.pth')))[0]
IndexError: list index out of range。
这种报错是不是checkpoint里面缺少文件导致的呢？现在的checkpoint里面只有model_81_STCFormer和model_27_STCFormer两个文件。期待您的回复，谢谢。 @zhenhuat

**Comment by zhenhuat** [comment]
> 您好，在运行命令 python demo/vis.py --video sample_video.mp4进行可视化的时候，请问checkpoint中要加入其他的文件嘛。运行的时候出现这个问题：Traceback (most recent call last): File "demo/vis.py", line 299, in get_pose3D(video_path, output_dir) File "demo/vis.py", line 147, in get_pose3D model_path = sorted(glob.glob(os.path.join(args.previous_dir, '*.pth')))[0] IndexError: list index out of range。 这种报错是不是checkpoint里面缺少文件导致的呢？现在的checkpoint里面只有model_81_STCFormer和model_27_STCFormer两个文件。期待您的回复，谢谢。 @zhenhuat

您好，我目前只释放了27帧和81帧的checkpoint，因为没有算力重新训练243了，你可以用已经释放的尝试。

**Comment by jianlai123-123** [comment]
你好，首先感谢您的解答。我在checkpoint中放了model_27_STCFormer和model_81_STCFormer两个文件，再次运行可视化命令时，还是出现错误：Traceback (most recent call last):
  File "demo/vis.py", line 300, in <module>
    get_pose3D(video_path, output_dir)
  File "demo/vis.py", line 147, in get_pose3D
    model_path = sorted(glob.glob(os.path.join(args.previous_dir, '*.pth')))[0]
IndexError: list index out of range
请问vis.py或者别的文件里面的代码要修改嘛。期待您的回复，谢谢。

**Comment by zhenhuat** [comment]
> 你好，首先感谢您的解答。我在checkpoint中放了model_27_STCFormer和model_81_STCFormer两个文件，再次运行可视化命令时，还是出现错误：Traceback (most recent call last): File "demo/vis.py", line 300, in get_pose3D(video_path, output_dir) File "demo/vis.py", line 147, in get_pose3D model_path = sorted(glob.glob(os.path.join(args.previous_dir, '*.pth')))[0] IndexError: list index out of range 请问vis.py或者别的文件里面的代码要修改嘛。期待您的回复，谢谢。

哈喽，代码应该是没有问题的，别人能跑出来。你需要逐行检查一下，路径是否正确之类的，比如这句`sorted(glob.glob(os.path.join(args.previous_dir, '*.pth')))` 有没有读取到文件

**Comment by jianlai123-123** [comment]
你好，感谢您的回答，可以运行起来了。还有一个问题想请教，运行可视化得到的是模型对输入视频的可视化结果，那么能同时得到相对应的GT可视化结果嘛。期待您的回复，谢谢。

**Comment by zhenhuat** [comment]
> 你好，感谢您的回答，可以运行起来了。还有一个问题想请教，运行可视化得到的是模型对输入视频的可视化结果，那么能同时得到相对应的GT可视化结果嘛。期待您的回复，谢谢。

当前的vis.py代码不可以，但是你可以在test的时候同时保存prediction和gt的结果，然后在本地绘制。

**Comment by jianlai123-123** [comment]
您好，关于可视化，按照您的意思是在运行python run_stc.py -f 27 -b 128  --train 0 --layers 6 -s 1 --reload 1 --previous_dir ./checkpoint/your_best_model.pth的时候，将run_stc.py文件中的划红线的部分保存到文件中，然后在本地读取是吗？请问保存什么样的格式能再本地比较好读取呢？读取以后使用matplotlib可视化工具吗？请问是这样的流程吗？期待您的回复，十分感谢。
<img width="611" alt="image" src="https://github.com/zhenhuat/STCFormer/assets/117512033/79c3bcc6-fbe2-4f04-ba5e-9160bc21e08d">

**Comment by zhenhuat** [comment]
对的，大概是在test的时候报这些保存到两个字典里，最后存为两个.mat就好了，具体需要你自己研究了。

**Comment by zhenhuat** [comment]
> 您好，关于可视化，按照您的意思是在运行python run_stc.py -f 27 -b 128 --train 0 --layers 6 -s 1 --reload 1 --previous_dir ./checkpoint/your_best_model.pth的时候，将run_stc.py文件中的划红线的部分保存到文件中，然后在本地读取是吗？请问保存什么样的格式能再本地比较好读取呢？读取以后使用matplotlib可视化工具吗？请问是这样的流程吗？期待您的回复，十分感谢。 <img alt="image" width="611" src="https://private-user-images.githubusercontent.com/117512033/302159979-79c3bcc6-fbe2-4f04-ba5e-9160bc21e08d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTI3NTIsIm5iZiI6MTcwNzExMjQ1MiwicGF0aCI6Ii8xMTc1MTIwMzMvMzAyMTU5OTc5LTc5YzNiY2M2LWZiZTItNGYwNC1iYTVlLTkxNjBiYzIxZTA4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwNTU0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZmRlMzJlOWZmNzk4MzA0YzgyNTlkYjhhODQ1NzI1YTU0Y2E4YjNkZjZmOTFjZDcwMDkyYWYzMTVmYjhlNjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WEJnAPocJbjZopSP-ztWA6wmwXRY4U5b6FS36LmkK4s">

对的，大概是在test的时候报这些保存到两个字典里，然后存为两个.mat就好了。在本地读取mat文件后，用matplotlib就可以绘制，具体需要你自己研究了。

**Comment by ZhiXia-SEU** [comment]
> 你好，感谢您的回答，可以运行起来了。还有一个问题想请教，运行可视化得到的是模型对输入视频的可视化结果，那么能同时得到相对应的GT可视化结果嘛。期待您的回复，谢谢。
你好，首先感谢您的解答。我在checkpoint中放了model_27_STCFormer和model_81_STCFormer两个文件，再次运行可视化命令时，还是出现错误：Traceback (most recent call last): File "demo/vis.py", line 300, in get_pose3D(video_path, output_dir) File "demo/vis.py", line 147, in get_pose3D model_path = sorted(glob.glob(os.path.join(args.previous_dir, '*.pth')))[0] IndexError: list index out of range 请问vis.py或者别的文件里面的代码要修改嘛。期待您的回复，谢谢
你好，请问这个问题是怎么解决的呀，demo里面的视频可以跑起来吗

**Comment by ZhiXia-SEU** [comment]
感谢，已解决
